import Testing
import Foundation
@testable import Arkyve

@Suite("libarchiveFormat Tests")
final class libarchiveFormatTests {
    @Test func testFormatValues() {
        // Test that all format values match their expected raw values
        #expect(libarchiveFormat.Unknown.rawValue == 0x0)
        #expect(libarchiveFormat.CPIO.rawValue == 0x10000)
        #expect(libarchiveFormat.CPIO_POSIX.rawValue == 0x10001)
        #expect(libarchiveFormat.CPIO_BIN_LE.rawValue == 0x10002)
        #expect(libarchiveFormat.CPIO_BIN_BE.rawValue == 0x10003)
        #expect(libarchiveFormat.CPIO_SVR4_NOCRC.rawValue == 0x10004)
        #expect(libarchiveFormat.CPIO_SVR4_CRC.rawValue == 0x10005)
        #expect(libarchiveFormat.CPIO_AFIO_LARGE.rawValue == 0x10006)
        #expect(libarchiveFormat.CPIO_PWB.rawValue == 0x10007)
        #expect(libarchiveFormat.SHAR.rawValue == 0x20000)
        #expect(libarchiveFormat.SHAR_BASE.rawValue == 0x20001)
        #expect(libarchiveFormat.SHAR_DUMP.rawValue == 0x20002)
        #expect(libarchiveFormat.TAR.rawValue == 0x30000)
        #expect(libarchiveFormat.TAR_USTAR.rawValue == 0x30001)
        #expect(libarchiveFormat.TAR_PAX_INTERCHANGE.rawValue == 0x30002)
        #expect(libarchiveFormat.TAR_PAX_RESTRICTED.rawValue == 0x30003)
        #expect(libarchiveFormat.TAR_GNUTAR.rawValue == 0x30004)
        #expect(libarchiveFormat.ISO9660.rawValue == 0x40000)
        #expect(libarchiveFormat.ISO9660_RR.rawValue == 0x40001)
        #expect(libarchiveFormat.ZIP.rawValue == 0x50000)
        #expect(libarchiveFormat.Empty.rawValue == 0x60000)
        #expect(libarchiveFormat.AR.rawValue == 0x70000)
        #expect(libarchiveFormat.AR_GNU.rawValue == 0x70001)
        #expect(libarchiveFormat.AR_BSD.rawValue == 0x70002)
        #expect(libarchiveFormat.MTREE.rawValue == 0x80000)
        #expect(libarchiveFormat.RAW.rawValue == 0x90000)
        #expect(libarchiveFormat.XAR.rawValue == 0xA0000)
        #expect(libarchiveFormat.LHA.rawValue == 0xB0000)
        #expect(libarchiveFormat.CAB.rawValue == 0xC0000)
        #expect(libarchiveFormat.RAR.rawValue == 0xD0000)
        #expect(libarchiveFormat._7ZIP.rawValue == 0xE0000)
        #expect(libarchiveFormat.WARC.rawValue == 0xF0000)
        #expect(libarchiveFormat.RAR_V5.rawValue == 0x100000)
    }

    @Test func testAsArkyveFormat() {
        // Test conversion to ArkyveFormats
        #expect(libarchiveFormat.Unknown.asArkyveFormat == nil)
        #expect(libarchiveFormat.Empty.asArkyveFormat == nil)
        #expect(libarchiveFormat.MTREE.asArkyveFormat == nil)
        
        #expect(libarchiveFormat.CPIO.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_POSIX.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_BIN_LE.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_BIN_BE.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_SVR4_NOCRC.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_SVR4_CRC.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_AFIO_LARGE.asArkyveFormat == .cpio)
        #expect(libarchiveFormat.CPIO_PWB.asArkyveFormat == .cpio)
        
        #expect(libarchiveFormat.SHAR.asArkyveFormat == .shar)
        #expect(libarchiveFormat.SHAR_BASE.asArkyveFormat == .shar)
        #expect(libarchiveFormat.SHAR_DUMP.asArkyveFormat == .shar)
        
        #expect(libarchiveFormat.TAR.asArkyveFormat == .tar)
        #expect(libarchiveFormat.TAR_USTAR.asArkyveFormat == .tar)
        #expect(libarchiveFormat.TAR_PAX_INTERCHANGE.asArkyveFormat == .tar)
        #expect(libarchiveFormat.TAR_PAX_RESTRICTED.asArkyveFormat == .tar)
        #expect(libarchiveFormat.TAR_GNUTAR.asArkyveFormat == .tar)
        
        #expect(libarchiveFormat.ISO9660.asArkyveFormat == .iso)
        #expect(libarchiveFormat.ISO9660_RR.asArkyveFormat == .iso)
        
        #expect(libarchiveFormat.ZIP.asArkyveFormat == .zip)
        #expect(libarchiveFormat._7ZIP.asArkyveFormat == ._7z)
        #expect(libarchiveFormat.AR.asArkyveFormat == .ar)
        #expect(libarchiveFormat.AR_GNU.asArkyveFormat == .ar)
        #expect(libarchiveFormat.AR_BSD.asArkyveFormat == .ar)
        #expect(libarchiveFormat.RAW.asArkyveFormat == .raw)
        #expect(libarchiveFormat.XAR.asArkyveFormat == .xar)
        #expect(libarchiveFormat.LHA.asArkyveFormat == .lha)
        #expect(libarchiveFormat.CAB.asArkyveFormat == .cab)
        #expect(libarchiveFormat.RAR.asArkyveFormat == .rar)
        #expect(libarchiveFormat.RAR_V5.asArkyveFormat == .rar)
        #expect(libarchiveFormat.WARC.asArkyveFormat == .warc)
    }

    @Test func testCanWrite() {
        // Test writable formats
        #expect(libarchiveFormat.TAR.canWrite)
        #expect(libarchiveFormat.TAR_USTAR.canWrite)
        #expect(libarchiveFormat.TAR_PAX_INTERCHANGE.canWrite)
        #expect(libarchiveFormat.TAR_PAX_RESTRICTED.canWrite)
        #expect(libarchiveFormat.TAR_GNUTAR.canWrite)
        #expect(libarchiveFormat.ZIP.canWrite)
        #expect(libarchiveFormat._7ZIP.canWrite)
        #expect(libarchiveFormat.ISO9660.canWrite)
        #expect(libarchiveFormat.ISO9660_RR.canWrite)
        #expect(libarchiveFormat.CPIO.canWrite)
        #expect(libarchiveFormat.CPIO_POSIX.canWrite)
        #expect(libarchiveFormat.CPIO_BIN_LE.canWrite)
        #expect(libarchiveFormat.CPIO_BIN_BE.canWrite)
        #expect(libarchiveFormat.CPIO_SVR4_NOCRC.canWrite)
        #expect(libarchiveFormat.CPIO_SVR4_CRC.canWrite)
        #expect(libarchiveFormat.CPIO_AFIO_LARGE.canWrite)
        #expect(libarchiveFormat.CPIO_PWB.canWrite)
        #expect(libarchiveFormat.XAR.canWrite)

        // Test non-writable formats
        #expect(!libarchiveFormat.Unknown.canWrite)
        #expect(!libarchiveFormat.Empty.canWrite)
        #expect(!libarchiveFormat.MTREE.canWrite)
        #expect(!libarchiveFormat.SHAR.canWrite)
        #expect(!libarchiveFormat.SHAR_BASE.canWrite)
        #expect(!libarchiveFormat.SHAR_DUMP.canWrite)
        #expect(!libarchiveFormat.AR.canWrite)
        #expect(!libarchiveFormat.AR_GNU.canWrite)
        #expect(!libarchiveFormat.AR_BSD.canWrite)
        #expect(!libarchiveFormat.RAW.canWrite)
        #expect(!libarchiveFormat.LHA.canWrite)
        #expect(!libarchiveFormat.CAB.canWrite)
        #expect(!libarchiveFormat.RAR.canWrite)
        #expect(!libarchiveFormat.RAR_V5.canWrite)
        #expect(!libarchiveFormat.WARC.canWrite)
    }

    @Test func testDescription() {
        // Test string descriptions
        #expect(libarchiveFormat.Unknown.description == "Unknown")
        #expect(libarchiveFormat.CPIO.description == "CPIO")
        #expect(libarchiveFormat.CPIO_POSIX.description == "CPIO_POSIX")
        #expect(libarchiveFormat.CPIO_BIN_LE.description == "CPIO_BIN_LE")
        #expect(libarchiveFormat.CPIO_BIN_BE.description == "CPIO_BIN_BE")
        #expect(libarchiveFormat.CPIO_SVR4_NOCRC.description == "CPIO_SVR4_NOCRC")
        #expect(libarchiveFormat.CPIO_SVR4_CRC.description == "CPIO_SVR4_CRC")
        #expect(libarchiveFormat.CPIO_AFIO_LARGE.description == "CPIO_AFIO_LARGE")
        #expect(libarchiveFormat.CPIO_PWB.description == "CPIO_PWB")
        #expect(libarchiveFormat.SHAR.description == "SHAR")
        #expect(libarchiveFormat.SHAR_BASE.description == "SHAR_BASE")
        #expect(libarchiveFormat.SHAR_DUMP.description == "SHAR_DUMP")
        #expect(libarchiveFormat.TAR.description == "BSD tar")
        #expect(libarchiveFormat.TAR_USTAR.description == "TAR_USTAR")
        #expect(libarchiveFormat.TAR_PAX_INTERCHANGE.description == "TAR_PAX_INTERCHANGE")
        #expect(libarchiveFormat.TAR_PAX_RESTRICTED.description == "TAR_PAX_RESTRICTED")
        #expect(libarchiveFormat.TAR_GNUTAR.description == "tar")
        #expect(libarchiveFormat.ISO9660.description == "ISO9660")
        #expect(libarchiveFormat.ISO9660_RR.description == "ISO9660 Rock Ridge")
        #expect(libarchiveFormat.ZIP.description == "Zip")
        #expect(libarchiveFormat.Empty.description == "Empty")
        #expect(libarchiveFormat.AR.description == "AR")
        #expect(libarchiveFormat.AR_GNU.description == "AR_GNU")
        #expect(libarchiveFormat.AR_BSD.description == "AR_BSD")
        #expect(libarchiveFormat.MTREE.description == "MTREE")
        #expect(libarchiveFormat.RAW.description == "RAW")
        #expect(libarchiveFormat.XAR.description == "XAR")
        #expect(libarchiveFormat.LHA.description == "LHA")
        #expect(libarchiveFormat.CAB.description == "CAB")
        #expect(libarchiveFormat.RAR.description == "RAR")
        #expect(libarchiveFormat._7ZIP.description == "7Zip")
        #expect(libarchiveFormat.WARC.description == "WARC")
        #expect(libarchiveFormat.RAR_V5.description == "RAR_V5")
    }

    @Test func testComparable() {
        // Test that formats can be compared
        #expect(libarchiveFormat.Unknown < libarchiveFormat.CPIO)
        #expect(libarchiveFormat.CPIO < libarchiveFormat.SHAR)
        #expect(libarchiveFormat.SHAR < libarchiveFormat.TAR)
        #expect(libarchiveFormat.TAR < libarchiveFormat.ISO9660)
        #expect(libarchiveFormat.ISO9660 < libarchiveFormat.ZIP)
        #expect(libarchiveFormat.ZIP < libarchiveFormat.Empty)
        #expect(libarchiveFormat.Empty < libarchiveFormat.AR)
        #expect(libarchiveFormat.AR < libarchiveFormat.MTREE)
        #expect(libarchiveFormat.MTREE < libarchiveFormat.RAW)
        #expect(libarchiveFormat.RAW < libarchiveFormat.XAR)
        #expect(libarchiveFormat.XAR < libarchiveFormat.LHA)
        #expect(libarchiveFormat.LHA < libarchiveFormat.CAB)
        #expect(libarchiveFormat.CAB < libarchiveFormat.RAR)
        #expect(libarchiveFormat.RAR < libarchiveFormat._7ZIP)
        #expect(libarchiveFormat._7ZIP < libarchiveFormat.WARC)
        #expect(libarchiveFormat.WARC < libarchiveFormat.RAR_V5)
    }
} 
